### ISSUE TITLE
Initial Steps

### ISSUE THREAD

**Issue by grechaw** [grechaw/hypothermia#1]
Making an app for android 

Tooling support

action item: Trevor to make github account.
action item: Fork https://github.com/grechaw/hypothermia

a simple game?  like mario, 2d platforms? 

Get intellij community edition

https://www.jetbrains.com/help/idea/getting-started-with-android-development.html

Download android SDK

https://developer.android.com/studio/install.html

"Build your first app"

**Comment by NorseGoat** [comment]
I am downloading IntelliJ Community Edition right now. I already have the Android SDK.

**Comment by grechaw** [comment]
Excellent, this is confirmation that the communications are in order.  Let me see if I can assign issues to you now, that was not previously working.

**Comment by grechaw** [comment]
cool, it worked.  Assign back to me when you have completed or need more info.

**Comment by grechaw** [comment]
If you include @grechaw in your comment ill get an email about it, I think.

**Comment by grechaw** [comment]
Hope you're feeling better @NorseGoat !

**Comment by NorseGoat** [comment]
@grechaw I now have IntelliJ and the SDK, what do I do ?

**Comment by NorseGoat** [comment]
@grechaw How do I fork Hypothermia? Is forking the same thing as cloning?

**Comment by grechaw** [comment]
I'm not all that sure on a good tutorial, but you're basically going to start to follow instructions in how to get an android app up and running.

Here's a video that looks worth watching -- it will generate some questions.  As soon as you have a question that will require my attention (you shouldn't expect quick responses generally). you can make a new issue in this project.

**Comment by grechaw** [comment]
https://www.youtube.com/watch?v=CbuoFxjAlgo

**Comment by grechaw** [comment]
forking is not cloning.  you'll fork , then clone that repo locally.

from your local clone you will be able to push to either fork, but you'll usually push to your fork.

**Comment by grechaw** [comment]
To fork, click 'fork' near the top right of github interface.

**Comment by grechaw** [comment]
I don't know how useful all of that video will be, you might want to skip parts.  but it will point out how you need an emulator

**Comment by NorseGoat** [comment]
@grechaw  How do I fork? Where is the option?

**Comment by NorseGoat** [comment]
@grechaw Ok I see the fork option

**Comment by NorseGoat** [comment]
@grechaw I forked it.  What do I clone now?

**Comment by grechaw** [comment]
Under your fork you will see a 'clone or download' link

https://github.com/NorseGoat/hypothermia.git

this is the URL of your codebase and this is what you will clone from within the IDE, intillij.  You will have to research how to do this, I'm not here to answer questions before you have researched some.  We can schedule our next meeting for you to make progress when you're unable to find answers in documentation for github or intellij.  

In intellij the way to clone will be to make a 'new project from source control'

**Comment by NorseGoat** [comment]
Do you have time talk to me on the phone? The process will go much faster

**Comment by grechaw** [comment]
I'm not available right now, no.  You don't need it to go faster, there's no hurry.

**Comment by NorseGoat** [comment]
Alright, I understand.

**Comment by NorseGoat** [comment]
@grechaw I am really sorry. I haven't been able to work on the project at all.  I didn't have any time because I was overwhelmed with German homework. I was constantly behind in German. Now I am done with my German class. I can work on the project now. I bought a book about android development.

**Comment by grechaw** [comment]
Hi @NorseGoat I've been wondering how you are and what's going on.  Congratulations on finishing german class.

**Comment by NorseGoat** [comment]
@grechaw I got pretty far on the tutorial for the game engine Defold. I followed all the steps and it is giving me an error. I really need your help. I know that you don't know about game engines, but I really need help or else I won't be able to do my project.

**Comment by grechaw** [comment]
Sounds good.  Please put into a new issue:

1. what you've done
2. what step is causing the error
3. What the error looks like

I'll be able to say something intelligent about it.

**Comment by NorseGoat** [comment]
Okay I will make a new issue when I get home from working.

**Comment by NorseGoat** [comment]
@grechaw I'm home from working with my Dad. I'm going to make the issue right now.

**Comment by NorseGoat** [comment]
@grechaw Hi Charles,
I have decided to abandon the idea of making a game because it is simply too difficult for me. Now I want to go back to the android app project idea, because I will be able to get help from you.

**Comment by grechaw** [comment]
Howdy @NorseGoat , delighted to hear from you.  Scoping the project is as you've learned very important, getting it to be the right size.

**Comment by grechaw** [comment]
This issue seems to have outlived its purpose, you are beyond initial steps.
